### ISSUE TITLE
Persist groups in edit assignments view

### ISSUE THREAD

**Issue by arkon** [MarkUsProject/Markus#1561]
This was first brought up by @david-yz-liu in issue https://github.com/MarkUsProject/Markus/issues/1552.

We want to allow instructors to choose to persist groups when editing an existing assignment, but what should happen if it was already persisted, then unchecked? By default, the "Students can work in groups" option wouldn't be checked, but the existing groups wouldn't be changed, which may contradict this.

(CC @reidka )

**Comment by reidka** [comment]
This needs further discussion but is related to #2237 and #2180.  

Right now, the persist groups button only shows up if "allow students to work in groups" is selected and there is another assignment that does not allow web submits and is a group assignment.

We have used the persist groups in the past to create the directories for individual assignments, but to avoid the problems in the comments above, I'd like ad this feature to the Groups tab, rather than the settings tab (as in #2180)
