### ISSUE TITLE
Submission can be marked as complete even if not all rubric criteria are marked

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#1919]
Haven't checked this for flexible criteria, though.

**Comment by peterzhao333** [comment]
@david-yz-liu I took a look at the grader's interface and just wanted to clarify some things about this issue. From what I understand it is referring to the Grader's interface for marking submissions, where the issue lies in that the grader can mark the submission as completed even if he has not assigned a grade to all criteria laid out in the marking rubric?

If that is the case, what should be the desired behaviour? An prompt (overridable?) notifying the user that not all criteria have been met? Or should submissions not be allowed to be marked as 'complete' unless all rubric criteria have been assigned a mark?

**Comment by david-yz-liu** [comment]
@peterzhao333 The change shouldn't be allowed at all. I'm fine with an alert appearing.
