### ISSUE TITLE
Rails 4 - PDF annotations don't work 

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#1941]
Looks like a PDF file in a submission won't render in the marking view. It will also prevent other (non-PDF) files from rendering.

**Comment by tsimica** [comment]
I suspect that the cause of this problem is because the PDF_SUPPORT isn't enabled by default in the configuration to convert the PDF's to JPG format. Looking into this one more...

**Comment by tsimica** [comment]
This was exactly the case. The PDF does not render when PDF_SUPPORT is false.

Steps to reproduce: 
- Upload a PDF file with the PDF_SUPPORT not enabled
- Collect all assignments and try viewing -- you will get an error because Rails will be unable to find the JPG

Fix:
- Enable PDF_SUPPORT
- Recollect any submissions as an instructor -- the trigger to convert PDF's to JPG's happens within the SubmissionCollector instance

**Comment by tsimica** [comment]
@david-yz-liu Consider closing? Not sure what else can be done if PDF_SUPPORT isn't enabled.

**Comment by david-yz-liu** [comment]
@tsimica Yep, makes perfect sense.
