### ISSUE TITLE
Flag empty submissions?

### ISSUE THREAD

**Issue by reidka** [MarkUsProject/Markus#2050]
It would be nice to be able to flag submissions where students have not submitted any files.  Sometimes this is easy to see based on the last commit date, but other times it is a bit trickier.

**Comment by reidka** [comment]
There are really two components to this issue:
One is to give the instructor the option of not assigning graders to empty submissions.
The other is to either use a different colour or a different status icon to show in the submissions table that the submission is empty.

**Comment by arkon** [comment]
Somewhat relevant: it'd be nice to have a different way of representing that a submission is collected too. The current design of just turning the row green doesn't really convey the message well, and I've had people ask me what it meant.

**Comment by melneubert** [comment]
@reidka Right now I've got a checkbox where the option to disallow adding graders to groups with empty submissions.

Would you prefer if I disallow this once the Admin tries to assign graders to group (and then notify them that the group does not have any files in their submission), or if I just hide groups with no submissions from the table so that an Admin can't even attempt to assign graders to them?

Also any input on the suggestion @arkon had? I've been trying to think of a good way to do this, right now all I can think of is to add another icon or something along those lines.

**Comment by reidka** [comment]
I like the checkbox.
Please don't hide groups.  That would confuse the instructors.   It would be good if there was a way to show that a group had a empty submission. Otherwise instructors will wonder why an assignment won't "take" a grader.
