### ISSUE TITLE
Setup pre-commit

### ISSUE THREAD

**Issue by oneohtrix** [MarkUsProject/Markus#2208]
To avoid all the annoying Hound message chains, we should setup [pre-commit](http://pre-commit.com/) hooks that verify all style changes before even committing.

**Comment by finnergizer** [comment]
I added this pre-commit hook to my Markus project to check for errors before it hits Hound.

It uses rubocop to verify all rake files that are modified in the commit (in their entirety) and rubocop-git to check the diffs of the remaining ruby files.

I had to add the `rubocop-git` gem to the Gemfile which only runs on the diffs of ruby files (otherwise I would see other rubocop errors if I modified a large file that existed before the introduction of rubocop to the project)

Steps:

1. From your main Markus directory run `vi .git/hooks/pre-commit`
2. Paste the following code into the file:
```
#!/usr/bin/env ruby

require 'English'
require 'rubocop'

changed_files = `git diff --cached --name-only --diff-filter=ACM`.split(/\n/).
    select { |file_name|
      File.extname(file_name) == '.rake'
    }.join(' ')

# first check the whole rake file that is modified
system("rubocop -c ./config/.rubocop.yml #{changed_files}") unless changed_files.empty?

if $CHILD_STATUS.to_s[-1].to_i != 0
    exit $CHILD_STATUS.to_s[-1].to_i
end

# now only check the diffs of remaining .rb files checked in
system("rubocop-git -c ./config/.rubocop.yml")
exit $CHILD_STATUS.to_s[-1].to_i
```
3. Modify your Gemfile to include `rubocop-git` as follows:
```
group :offline do
  gem 'railroady'
  gem 'rdoc'
  gem 'rubocop'
  gem 'rubocop-git'
  gem 'thin'
end
```
4. Run `bundle install` to install rubocop-git

Now anytime you run git commit, this ruby script will be called and execute the rubocop checks. It will not commit if it encounters rubocop errors. _If you want to commit anyways, run_

`git commit --no-verify`

**Comment by david-yz-liu** [comment]
@finnergizer Maybe I'm doing this wrong, but it seems to have run the check and not caught any style errors I put in. Can you please give an example of an error this catches?

**Comment by finnergizer** [comment]
@david-yz-liu Did you run the check by running the script or doing a git commit? It should check files staged for commit (i.e. those that have been added via git add)? 

For example it just ran when committing some of files for seeding and I got the following errors back (I assume based on what is defined in our .rubocop.yml):

```
lib/tasks/grade_entry_forms.rake:35:7: C: Redundant curly braces around a hash parameter.
      {name: "Q3", out_of: 8, position: 3})
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/tasks/grade_entry_forms.rake:35:7: C: Space inside { missing.
      {name: "Q3", out_of: 8, position: 3})
      ^
lib/tasks/grade_entry_forms.rake:35:14: C: Prefer single-quoted strings when you don't need string interpolation or special symbols.
      {name: "Q3", out_of: 8, position: 3})
             ^^^^
lib/tasks/grade_entry_forms.rake:35:42: C: Space inside } missing.
      {name: "Q3", out_of: 8, position: 3})
```

What kind of output do you get?
