### ISSUE TITLE
Allow a GradeEntryForm to be created with no columns (GradeEntryItems) more easily

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#3359]
Right now a blank nested form for a GradeEntryItem appears by default, and if you leave it blank when creating a GradeEntryForm, the validation fails.

A fix could be to ignore blank GradeEntryItem input fields in the controller when the form is submitted.

**Comment by czack810150** [comment]
Should the red * beside "name" and "out_of" be removed? I think it makes sense either way because when both fields are not filled, they are not required(validations ignored), but if one of the fields are specified, then the other one becomes required.

Screenshot: 
<img width="538" alt="screen shot 2018-05-17 at 1 47 21 pm" src="https://user-images.githubusercontent.com/17039493/40194583-f1a8757e-59d8-11e8-83a9-bef387c3ccd1.png">

**Comment by david-yz-liu** [comment]
Ah, sure that's fine to remove them.

**Comment by czack810150** [comment]
As discussed on Slack with David, the UI will stay as is.
