### ISSUE TITLE
Hide .gitkeep in assignment subdirectories

### ISSUE THREAD

**Issue by david-yz-liu** [MarkUsProject/Markus#3361]

**Comment by amrrsharaff** [comment]
Hi, I will work on this issue.

**Comment by reidka** [comment]
This isn't really an easy fix.

1. First question is where to hide the subdirectories: student view, instructor view, TA view
2. Next question is changing the code so that a directory that only has a .gitkeep file in it is empty for the purposes of auto-testing or whether a student has submitted it.

**Comment by reidka** [comment]
Alessio recommends to create a new global variable in the git_repository code to avoid hard-coding the name.

**Comment by david-yz-liu** [comment]
The file should be hidden for the student and grading views. It can be displayed in the repo browser.
