### ISSUE TITLE
Number of Grading Assignments Completed is Larger than Total Allotted

### ISSUE THREAD

**Issue by reecemartin** [MarkUsProject/Markus#4200]
I have been assigned 26 assignments to grade, if I start grading from the back (number 26) I see this at the top of the screen.

29/26 Complete

**Comment by mishaschwartz** [comment]
Hi @reecemartin,

I am unable to recreate this issue with the information you have given. I just see 4/26 (or some other value less than 26) in each view where this counter is displayed. 

If you can add any additional information that can be used to recreate your problem that would be useful:

- which MarkUs instance does this problem occur in (which course are you a TA for?)
- how many assignments have you graded when the problem occurs?
- which page does the problem occur on? (screenshots are helpful)
- does this problem persist when you grade at least 1 assignment?

Thanks

**Comment by reecemartin** [comment]
If you modify the grades of students you can sometimes see it, I also saw 119/26.

<img width="405" alt="Capture" src="https://user-images.githubusercontent.com/1767743/68063625-e53b6d00-fce8-11e9-8b03-eac9abc0adff.PNG">

**Comment by Xyene** [comment]
In case it's of any value, I can say this also happens to me. An uninformed guess would be that it's sometimes counting other TA's current completions as my own, since it doesn't happen when I'm marking at unusual hours. That could be just coincidence, though.

(I'm a TA for CSC369, and it seems to happen at any number of assignments marked.)
