### ISSUE TITLE
Feature request: for "This group submitted work after the due date." message, distinguish based on whether work is collected

### ISSUE THREAD

**Issue by colinmorris** [MarkUsProject/Markus#4459]
When I'm browsing assignment submissions and I see the message "This group submitted work after the due date.", there are two (to me, very different) cases:

1. The submission I'm currently looking at is their last submitted version. Either because they submitted during some penalty period before I mass-collected submissions, or they submitted after that, but I already manually collected their latest version. In either case, usually no action is required from me.
2. The submission I'm looking at is not their last submitted version. If this is the case, I really want to know about it. It usually means I granted this student an extension and I still need to manually collect their latest version, or something weird happened that I want to know about (and possibly contact the student about). 

So it would be very helpful to me if there were two messages that distinguished between these cases. e.g.

> This work was submitted after the due date

vs. 

> This group has uncollected work submitted after the due date

(Or if there's any existing way to systematically check for the existence of uncollected submission versions, that could also scratch the same itch.)

**Comment by mishaschwartz** [comment]
Just to clarify one thing, in case number 2: are you giving these students an extension on MarkUs or are you saying that you're keeping track of their extensions off-site and not using MarkUs to manage extensions?

**Comment by colinmorris** [comment]
My process is to track extensions off-site, and then for students with an extension, I'll either grab their latest version by going to their repository and clicking "Collect and grade this revision" (without checking the "Apply late penalty" box), or, if they submitted during the penalty period, I'll remove the deduction in the "Summary" tab of the submission view.

(I'm not sure if that counts as managing the extensions within MarkUs or not. If there were a way to set individualized deadlines for certain students/groups, I would definitely be interested in this, but I'm not aware of this feature existing.)

**Comment by mishaschwartz** [comment]
Ok I understand. There is actually a way of setting extensions in MarkUs. This essentially modifies the deadline for a single group of students for a given assignment. Then, when you go to collect the submissions you don't have to do it manually for each student with an extension, MarkUs will collect the correct revision automatically for each group.  

I realize that it's a new feature since version 1.8.1 and adding the info to the wiki is still on the TODO list (I'll get that added shortly).

For now, you can add extensions for individual groups by:

- go to the "Groups" tab for you assignment
- find the group you want to give the extension to on the table on the right-hand-side of the page
- click the (+) icon for that group, a modal will pop up where you can say how long the extension is for (in weeks, days, hours, ...)

I'm still going to leave this issue up though because having clearer messages to graders about the state of the student submissions is still a good idea. Thanks

**Comment by mishaschwartz** [comment]
wiki now contains info about giving groups an extension:

https://github.com/MarkUsProject/Markus/wiki/Instructor-Guide--Groups#give-a-group-an-extension
