### ISSUE TITLE
After given an extension, I am not able to see the assignment submission page

### ISSUE THREAD

**Issue by MaT1g3R** [MarkUsProject/Markus#4824]
I have been given an extension for an assignment, however, I am not able to see the submissions tab on Markus UI:

![image](https://user-images.githubusercontent.com/15258494/90837461-1e98a400-e320-11ea-9d1c-d196cc96c7fa.png)

Appending `/submissions/file_manager` manually to the URL results in a 302 redirect back to the assignment page

**Comment by dijkstracula** [comment]
For context, the person who filed this issue is in my class this summer.  We discovered that their submission for one of the assignments was missing and were trying to figure out if it was mistakingly just not submitted on the client side, if it was submitted but there exists a UI issue on my end where it isn't being collected in the standard way, or (terrifyingly) if it was submitted but somehow got dropped.  I worry that if it's not the first case, there may exist other students who expected to have submitted their work.

Is it perhaps possible that any server-side logging could be checked around 7 August to see if anything exceptional happened on the backend?  @MaT1g3R , do you have a rough idea of when you submitted (and, was it through the webapp or version control?)

**Comment by MaT1g3R** [comment]
If I was to guess, I probably submitted it on 2020-07-27 around 15:30

**Comment by mishaschwartz** [comment]
Hi @MaT1g3R, from the screenshot you sent me it looks like you have not created a group for this assignment. You must create a group first in order to submit anything which should explain why the submissions tab is not visible. Is it possible that you submitted your work for the asn2 assignment to a different assignment by mistake? With the current setup, you should not have been able to submit anything through the UI to the asn2 assignment.

**Comment by dijkstracula** [comment]
That seems unlikely; generally, I specify exact filenames that I want submitted, and this assignment's filenames would be unique to the course.

**Comment by dijkstracula** [comment]
Also, I notice that when I go to create @MaT1g3R 's "group of one" manually, I get a message saying "Group was successfully created.", but the student's group does not appear in the list of groups.

**Comment by mishaschwartz** [comment]
Closing because this is related to MarkUs usage for an individual instance, not the MarkUs software itself.

@dijkstracula I will contact you offline to resolve this specific case.
