### ISSUE TITLE
Can't collect before extended due date from submission screen

### ISSUE THREAD

**Issue by dijkstracula** [MarkUsProject/Markus#4829]
I have an asynchronous final assessment in my course this term.  It was suggested that I be able to collect submissions to hand to the graders as they come in through MarkUs in the following way:

* Set the deadline to the _beginning_ of the assessment period
* Make an extension to the _end_ of the assessment period.

From the "submissions" page, when I try to collect submitted exams, I get the "Could not collect submissions for some groupings and assignment fas - the collection date has not been reached for these groupings." error.  However, by going to each individual submission in the repo browser, clicking "collect and grade" does work.

It'd be nice if this was consistent between the two pages, as collecting each individual one by hand is slightly tedious.

Thanks!

**Comment by mishaschwartz** [comment]
This is the intended behaviour. Collecting submission in bulk (from the submissions table) should only collect for groups where the submission deadline has passed (this includes all extensions and penalty periods). 
The manual collection option (from the repo browser) allows the instructor to collect any submission at any time. 

It seems that you would like to have an option to collect submitted work before the submission deadline as long as the student has submitted _any_ work to MarkUs. This is not a behaviour we plan on supporting because it would require MarkUs to differentiate between a student who has submitted work in progress before the deadline from a student who has submitted a finalized version of their assignment.
