### ISSUE TITLE
Please disable the escape key when entering annotations

### ISSUE THREAD

**Issue by khers** [MarkUsProject/Markus#4914]
I am a vim user and the esc key is muscle memory.  When entering annotations hitting esc discards the inputted text.  Can we get a confirmation dialog or better yet ignore the key press?

**Comment by mishaschwartz** [comment]
Using escape to exit a modal is a very common UI pattern and every other modal in MarkUs can be closed in this way. Because of this, disabling the escape key is not an option for us. 

However, we have noted the issue and will take this into consideration when we update the modals themselves; it may be a good idea to allow text to persist in the text-box even when the modal is closed, at least until the page refreshes.
