### ISSUE TITLE
Feature request: defer rendering of large files

### ISSUE THREAD

**Issue by st-tran** [MarkUsProject/Markus#5404]
Currently, the submissions file viewer always renders the file when the page is loaded. For small files this is not an issue, but larger files take very long to load, causing the page to freeze completely. When grading students who've missed a file or uploaded to the wrong directory, this is a major inconvenience.

A workaround is to quickly navigate to another file before the file is rendered, but it would be useful to have an option (button?) to only render the contents when requested by the viewer.

**Comment by mishaschwartz** [comment]
Thanks for raising this issue. 

I don't think the best solution is to not render the file when the page is loaded, just in case the file is exceptionally large (or internet is slow, etc.). However, we can be better at loading large files asynchronously so that the rest of the page is functional while the file itself is loading.

**Comment by mishaschwartz** [comment]
We should also set limits on large files and only display files that are under X bytes. In this case X can be a different number for text vs. binary files.

If files are too large we should display a message that says something like "this file is too large to display, please download it to view"
