### ISSUE TITLE
Double Negatives in Checkboxes

### ISSUE THREAD

**Issue by dan1982code** [MarkUsProject/Markus#5573]
If you click on Assignments, then choose an assignment, then click Graders, there are these two checkboxes:

 Do not assign graders to groups with empty submissions (requires that submissions are collected)
 Do not show group information to graders

The 'do not' with the checkboxes always makes me think twice (reversing what the checks mean). Also, the parenthetical portion in the first one, I wonder if that has to do with when it is checked or not checked.

Instead, maybe we could have

assign graders to groups with empty submissions (unchecking this box requires that submissions are collected)
show group information to graders

**Comment by mishaschwartz** [comment]
I agree that it's clearer to remove the "Do not" but I think that it's important that the default values are unchecked. What if we use:

- Assign graders to groups with empty submissions
- Hide group membership information from graders

I also think that parenthetical info should be moved to a tooltip since it's too verbose and confusing as it is currently

**Comment by dan1982code** [comment]
Thank you -- I think this would work well.
