### ISSUE TITLE
Broken download functionality 

### ISSUE THREAD

**Issue by gabmorg** [MarkUsProject/Markus#5667]
While the download button exists, the clickable_text does not actually lead to a file download (or anything, currently, based on the inspected element)

![image](https://user-images.githubusercontent.com/5216871/145853228-f2c63d15-86f4-4650-9599-48307fe1cd6b.png)
![image](https://user-images.githubusercontent.com/5216871/145853271-f7ccf3af-d981-4f71-beaf-d76ceec8f377.png)
![image](https://user-images.githubusercontent.com/5216871/145853675-69bfaea0-b47c-44b2-8316-be6ff7138572.png)

**Comment by mishaschwartz** [comment]
Sorry just getting to this now. This looks like a policy issue where graders who have been given permission to manage assignments do not have permission to download or upload assignments or grades.

In order to resolve this we should revisit this policy and decide whether graders with assignment management permissions should be able to download/upload in these cases:

- If they should be allowed then we should enable these links for graders
- If they shouldn't be allowed then we should hide these modals entirely to avoid confusion

**Comment by mishaschwartz** [comment]
We are going to go with the following changes:

- For each of the views that provide a download modal, the user should be able to download a csv/yml file that contains the same content that is visible on the webpage.
- This means that a grader that has only been assigned 10 students to grade (for example) will only be able to download the grades for those 10 students from the grade entry form view.
