### ISSUE TITLE
Statistics page

### ISSUE THREAD

**Issue by mishaschwartz** [MarkUsProject/Markus#5831]
Right now we show general statistics about individual assignments on the dashboard page but it would be interesting to show course wide statistics in a separate view (visible to instructors).

Where to find ideas of what sort of statistics to show on this page:

- Look at other LMS software and see what they do (canvas, blackboard, moodle, etc.)
- Talk to instructors and other MarkUs users about what would be useful for them
- Talks to other MarkUs developers about what sort of statistics are available

due date: end of summer 2022 (so it can be included in version 2.2.0)

**Comment by anoverga17** [comment]
This issue is now resolved. Rather than creating a general course wide statistics survey, results from a MarkUs survey conducted showed instructors would rather want more specific and clearer summary statistics. Now that these summary statistics are enhanced this issue is now resolved. 

The only thing statistics related left that may require a bit of thought is user analytics which are described in a separate pull request [here](https://github.com/MarkUsProject/Markus/issues/6190)
