### ISSUE TITLE
Marks Spreadsheet Upload sensitive to filename

### ISSUE THREAD

**Issue by treblacy** [MarkUsProject/Markus#5961]
For a marks spreadsheet, in the Grades tab, when using the Upload function:

If I have a file with filename "h.csv" and its content conforms to the required file format, uploading succeeds and I can see the data showing up.

If the filename is "h", same content, just a renaming, it's a "The selected file was improperly formed".

Ugh is this intended?

I'm at U of Toronto Scarborough, MarkUs version 1.14.0.DEV

**Comment by mishaschwartz** [comment]
Thanks for the bug report!

Markus relies on the file extension to determine how to handle the upload since we support multiple file types. In this case though I believe the only acceptable file type is `.csv` so we can probably safely just assume that all uploaded files will be csvs. 

For now, please continue naming your files with file extensions and we'll figure out the best way to handle this in a future version.

**Comment by david-yz-liu** [comment]
Closed in #6961
