### ISSUE TITLE
Disallow non-AssignmentFiles option in Assignment Properties

### ISSUE THREAD

**Issue by benjaminvialle** [MarkUsProject/Markus#76]
From Byron:

"Should have an option when setting up the assignment whether files not listed in the assignment spec will be accepted."

This goes against our "accept all" policy. Might have to ask Karen about this.

**Comment by MatakuT** [comment]
I'm working on it :)

**Comment by MatakuT** [comment]
Almost done - the skeleton is working, just have to work on the checkbox message. Got stuck with making an option for disallowing non-assignment files to show in the right place under the right action. My goal is to show the checkmark after clicking on "Add a Required File". I made a flag (false) in the controller that is passed to the assignment form, then to the helper method responsible for processing the mini-form triggered by clicking on "Add a Required File". Then in the helper method the flag is set to true and passed to the partial rendered by the original form. If the value is true then the checkbox is shown, otherwise it's hidden. The problem is that this helper method is called independent from whether "Add a Required File" is clicked, so the flag is set to true every time the assignment form is rendered. It has to only be set to true if the partial form is rendered - I still have to find the rule/way for checking that.

**Comment by MatakuT** [comment]
done and pushed
