### ISSUE TITLE
Use correct HTTP status code for expired sessions

### ISSUE THREAD

**Issue by divarvel** [MarkUsProject/Markus#764]
Currently, the page telling the user about his expired session is served with a 200 status code, which is misleading, especially when downloading stuff automatically.

Steps to reproduce :

Try to load a page with an expired session.
The response page is served with a 200 OK status code.

It should be a 401 status code instead.

**Comment by david-yz-liu** [comment]
@Eitredes Can you take a look at this one?

**Comment by Eitredes** [comment]
Already on it.

**Comment by Eitredes** [comment]
@david-yz-liu When I set the redirect's status as unauthorized, Rails automatically inserts a "You are being redirected" page with a link to the login screen. Do we want this behaviour added (probably with the page prettied up, since it's just some 12pt times new roman), or should I route around it?

**Comment by david-yz-liu** [comment]
Eh, I'm okay with the current behaviour (automatic redirect to the login page).

**Comment by david-yz-liu** [comment]
Closed for now, doesn't seem to be worth the trouble. Would be interesting to look into the "Rails best practice" for this, but a quick Google search didn't turn up anything substantial.
